services:
  scoutarr:
    image: ghcr.io/statichum/scoutarr-fm
    container_name: scoutarr-fm
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./config/:/config/
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - "8787:8787"
